name: Build UHFDemo EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Retarget Project to .NET 4.8
      # Цей скрипт автоматично замінює стару версію фреймворку на актуальну 4.8 всередині файлу проекту
      run: |
        (Get-Content UHFDemo/UHFDemo.csproj) -replace '<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>', '<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>' | Set-Content UHFDemo/UHFDemo.csproj
      shell: powershell

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore uhfreader.sln
      continue-on-error: true

    - name: Build UHFDemo Project Only
      run: msbuild UHFDemo/UHFDemo.csproj /p:Configuration=Release /v:m

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UHFDemo-Compiled
        path: |
          **/bin/Release/
          **/bin/x86/Release/
