name: Build UHFDemo EXE

on:
  workflow_dispatch: # Дозволяє запустити збірку вручну кнопкою

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore uhfreader.sln

    - name: Build Solution
      run: msbuild uhfreader.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UHFDemo-Compiled
        path: |
          **/bin/Release/
